### ISSUE TITLE
Append to array or collection of a component configuration 

### ISSUE THREAD

**Issue by joeitu** [LinkedSoftwareDependencies/Components.js#113]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

( From #112 )

The motivation is when you have to write two separate components that both need to add a key/value to an array of a component config. 

Currently, the only way to achieve this is by overriding the component config, which is problematic when to independent component wants to append ( and therefore override ) the same array. 

An example with two CSS components:
`ModuleOne` needs to add its own js script to CSS' `well-known` folder. To achieve that it will override  `urn:solid-server:default:StaticAssetHandler` in [`config/http/static/default.json`](    https://github.com/CommunitySolidServer/CommunitySolidServer/blob/ba19a42a194cb3d70e0674a404e43c07e9cc24ef/config/http/static/default.json#L10)
`ModuleTwo` needs to do the same.
When adding both `ModuleOne` and `ModuleTwo` to the CSS graph, only the script from `ModuleTwo` will be available in the `well-known` folder. Because `ModuleOne` override will be in turn overridden by `MoculeTwo`.

**Comment by joachimvh** [comment]
Closing as this can be done as discussed in the linked issue.
