### ISSUE TITLE
Throw error when import is not found

### ISSUE THREAD

**Issue by pheyvaer** [LinkedSoftwareDependencies/Components.js#14]
It would be good to throw an error when an import is not found. At the moment it looks like imports that are not found are silently ignored.

**Comment by rubensworks** [comment]
Just looked into this again, and it looks like we are already doing this.

Perhaps the problem here was that the `import` keyword was used incorrectly, maybe without the proper context (`"https://linkedsoftwaredependencies.org/bundles/npm/componentsjs/^3.0.0/components/context.jsonld"`)
