### ISSUE TITLE
Migrate to n3 1.x

### ISSUE THREAD

**Issue by RubenVerborgh** [LinkedSoftwareDependencies/Components.js#15]
We currently depend on a pre-RDF/JS version of N3.js.

This would allow better deduping and even tree shaking (since N3.js 1.2.0) in webpacked code.

**Comment by rubensworks** [comment]
Related to #1.

**Comment by jacoscaz** [comment]
Just stumbled into this myself on my quest to produce the smallest possible `comunica` bundle for `quadstore`, it would definitely be nice to have a 1.x of `n3` version in `componentsjs`. I'll try to have a look in the coming weeks.

**Comment by rubensworks** [comment]
I've actually started working on this yesterday :-)
