### ISSUE TITLE
Incompatible with rollup

### ISSUE THREAD

**Issue by retog** [LinkedSoftwareDependencies/Components.js#18]
As this package uses a very old version of n3.js it inherits this issue: 
https://github.com/rdfjs/N3.js/issues/134

**Comment by rubensworks** [comment]
This package is not functional in the browser, as it makes use of file IO and package.json scanning.

How are you attempting to use this package in the browser?

**Comment by retog** [comment]
It came as a pendency of `@comunica/actor-init-sparql`

**Comment by rubensworks** [comment]
I haven't tested Comunica with Rollup, but when using it with Webpack, Components.js will be tree-shaked out. Are you aware of any such functionality in Rollup?

It may also be caused by the way you use Comunica. Do you have your code available somewhere online?

**Comment by retog** [comment]
here you go: https://github.com/retog/rollup-comunica

**Comment by rubensworks** [comment]
Thanks for the example repo. I've moved this issue to https://github.com/comunica/comunica/issues/656
