### ISSUE TITLE
Failure on Node 10: Cannot find module '@solid/community-server'

### ISSUE THREAD

**Issue by RubenVerborgh** [LinkedSoftwareDependencies/Components.js#22]
When running https://github.com/solid/community-server/pull/358 on Node 10, it fails with

```
{ Error: Cannot find module '@solid/community-server'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at MappedNamedComponentFactory.<anonymous> (/home/runner/work/community-server/community-server/node_modules/componentsjs/lib/factory/UnnamedComponentFactory.js:197:43)
    at Generator.next (<anonymous>)
    at /home/runner/work/community-server/community-server/node_modules/componentsjs/lib/factory/UnnamedComponentFactory.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/community-server/community-server/node_modules/componentsjs/lib/factory/UnnamedComponentFactory.js:3:12)
    at Promise (/home/runner/work/community-server/community-server/node_modules/componentsjs/lib/factory/UnnamedComponentFactory.js:179:49)
    at new Promise (<anonymous>) code: 'MODULE_NOT_FOUND' }
```

It works fine on Node 12.

I also think i did encounter this error on Node 12 in a different circumstance, but I cannot remember/reproduce.

Not urgent, since we will drop Node 10 anyway.

**Comment by rubensworks** [comment]
Probably not applicable anymore in the rewrite, but will look into it in any case then.

**Comment by joachimvh** [comment]
Currently running into this consistently with node v12.14.1. Did a clean install and rebuild. Also tried deleting the package-lock.json and installing but then there are some typescript compilation problems due to a newer version so didn't go further down that path.

**Comment by joachimvh** [comment]
Can confirm that it is fixed after upgrading to node 14 though.

**Comment by RubenVerborgh** [comment]
> a clean install

Also a `git clean -fx .`? That makes the difference for me.

**Comment by joachimvh** [comment]
Did the following steps:
```
git clean -fx .
npm ci
npm start
```
and got the error.

**Comment by RubenVerborgh** [comment]
Same on a clean checkout?

**Comment by joachimvh** [comment]
```
git clone git@github.com:solid/community-server.git
cd community-server
npm ci
npm start
```
Still got the error (again on the node 12 version of above of course). This is not the latest node 12 version so it could be a special edge case problem with that version of course.

**Comment by rubensworks** [comment]
@joachimvh Do you know at what point it fails? Because AFAIK, this used to work on Node 12. So something must have changed in the configs, which would be good to know for debugging Components.js.

**Comment by joachimvh** [comment]
The call to `await loader.instantiateFromUrl` caused the error above to be thrown. It definitely used to work on that version since that is the node version I have been running for the entire development so far 😃

**Comment by rubensworks** [comment]
Ok, but I'm referring to the config changes in CSS that caused the breakage, as it used to work before as you mentioned :-)

**Comment by joachimvh** [comment]
Ah, you meant point in time 😄. I actually have no idea. I just noticed this morning that the server wouldn't start anymore but I can't say exactly when it started failing. I would have to go through the commit history and try them out.

**Comment by rubensworks** [comment]
`git bisect` may help here :-)

**Comment by joachimvh** [comment]
Did a bisect run
```
0407a3649077d14c85b74a476146e9d7c73d1996 is the first bad commit
commit 0407a3649077d14c85b74a476146e9d7c73d1996
Author: Ruben Verborgh <ruben@verborgh.org>
Date:   Thu Nov 26 20:09:23 2020 +0100

    feat: Add DPoPWebIdExtractor.
```

**Comment by rubensworks** [comment]
Nothing special going on there. I suspect this won't be an issue anymore with the (better tested) version of Components.js though. But will check it in any case.

For reference: https://github.com/solid/community-server/commit/0407a3649077d14c85b74a476146e9d7c73d1996

**Comment by joachimvh** [comment]
Might be because the external library that gets introduced there has problems with the node version causing it to not be instantiated?

**Comment by rubensworks** [comment]
> Might be because the external library that gets introduced there has problems with the node version causing it to not be instantiated?

That could indeed be the case. If true, then the real issue is that error reporting here just goes wrong, as the original error is swallowed.
