### ISSUE TITLE
How to develop a local module?

### ISSUE THREAD

**Issue by RubenVerborgh** [LinkedSoftwareDependencies/Components.js#29]
I am working on an external module to `@solid/community-server`. My module is named `solid-hue`; not yet published on npm.

I start creating my configuration `config-hue.json` as follows:

```json
{
  "@context": [
    "https://linkedsoftwaredependencies.org/bundles/npm/solid-hue/^0.0.0/components/context.jsonld",
    "https://linkedsoftwaredependencies.org/bundles/npm/@solid/community-server/^1.0.0/components/context.jsonld"
  ]
}
```

However, when running the command `community-solid-server -c config/config-hue.json`, I get:

```
  jsonld.InvalidUrl: Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.
      at Array.done (/Users/ruben/Documents/UGent/Solid/solid-community-server/node_modules/jsonld/js/jsonld.js:6841:19)
```

This is understandable, given that `@solid/community-server` does not know about the `package.json` contents of my `solid-hue`, which has the local aliases:

```
  "lsd:module": "https://linkedsoftwaredependencies.org/bundles/npm/solid-hue",
  "lsd:components": "dist/components/components.jsonld",
  "lsd:contexts": {
    "https://linkedsoftwaredependencies.org/bundles/npm/solid-hue/^0.0.0/components/context.jsonld": "dist/components/context.jsonld"
  },
  "lsd:importPaths": {
    "https://linkedsoftwaredependencies.org/bundles/npm/solid-hue/^0.0.0/components/": "dist/components/",
    "https://linkedsoftwaredependencies.org/bundles/npm/solid-hue/^0.0.0/config/": "config/",
    "https://linkedsoftwaredependencies.org/bundles/npm/solid-hue/^0.0.0/dist/": "dist/"
  },
```

What would be a convenient way for developers to resolve this?

**Comment by RubenVerborgh** [comment]
PS My current workaround is to run a local webserver and to use `http://127.0.0.1:5000/dist/components/context.jsonld` as the context. One solution _could_ be to run a local webserver that exposes the globally installed / symlinked packages. Although I hope there is something more simple.

**Comment by RubenVerborgh** [comment]
However, with that workaround, I still get:

```
Error: Could not run config _:b1bnode183 because exactly one valid component type was expected, while 0 were found in the defined types [https://linkedsoftwaredependencies.org/bundles/npm/solid-hue/dist/HueStore#HueStore]. Alternatively, the requireName and requireElement must be provided.
Found: Resource {
  value: '_:b1bnode183',
  termType: 'BlankNode',
  'http://www.w3.org/1999/02/22-rdf-syntax-ns#type': [
    Resource {
      value: 'https://linkedsoftwaredependencies.org/bundles/npm/solid-hue/dist/HueStore#HueStore',
      termType: 'NamedNode'
    }
  ],
  types: [
    Resource {
      value: 'https://linkedsoftwaredependencies.org/bundles/npm/solid-hue/dist/HueStore#HueStore',
      termType: 'NamedNode'
    }
  ]
}
All available usable types: [
// lots of these:
https://linkedsoftwaredependencies.org/bundles/npm/@solid/community-server/dist/authentication/BearerWebIdExtractor#BearerWebIdExtractor,
// lots of these:
https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-abstract-mediatyped/Actor/AbstractMediaTyped,
// also these:
https://linkedsoftwaredependencies.org/bundles/npm/rdf-parse/RdfParser,
https://linkedsoftwaredependencies.org/bundles/npm/rdf-dereference/RdfDereferencer,
https://linkedsoftwaredependencies.org/bundles/npm/rdf-serialize/RdfSerializer
]
```

But not my `https://linkedsoftwaredependencies.org/bundles/npm/solid-hue`, presumably because it's not in the `package.json` dependencies of `@solid/community-server`.

**Comment by RubenVerborgh** [comment]
The only thing that worked at the moment is modifying the `package.json` of `@solid/community-server` to include the local aliases.

I presume a solution could be to do something like `community-solid-server -c config/config-hue.json --loadPackage .` or so, where the `loadPackage` option then passes extra `package.json` files to Components.js, supplying additional `lsd:contexts` and `lsd:importPaths`.

**Comment by RubenVerborgh** [comment]
Solved via https://github.com/solid/community-server/commit/ba4f7ff26c77636f7b367de316409001cd173692, such that I can now call:

```shell
community-solid-server -c config/config-hue.json -m . -g
```
or
```shell
community-solid-server -c config/config-hue.json --mainModulePath . --globalModules
```

Do you think this is the appropriate solution?

The `--globalModules` flag (corresponding to the `scanGlobal` setting) is needed until #30 is resolved.

**Comment by rubensworks** [comment]
> PS My current workaround is to run a local webserver and to use http://127.0.0.1:5000/dist/components/context.jsonld as the context.

If the packages are properly linked to each other, this should not be needed.
Components.js will resolve contexts via the file system if possible.

> Do you think this is the appropriate solution?

Modifying the main module path is indeed the way to go (that's also how Comunica handles init from external modules ([example](https://github.com/comunica/comunica-actor-init-sparql-hdt/blob/master/bin/query-dynamic.ts)).

`scanGlobal` should however not be needed, but let's follow up on that in #30.
FYI `scanGlobal` has been removed in the new version (because it's unstable and slow).

**Comment by RubenVerborgh** [comment]
Thanks!

>  FYI `scanGlobal` has been removed in the new version (because it's unstable and slow).

I do like it though; slow wouldn't be a problem (if you choose the option), but unstable of course is.

**Comment by RubenVerborgh** [comment]
Turns out the easy solution was just prefixing it with `npx` 🤦‍♂️

```
npx community-solid-server -c config/config-hue.json
```

**Comment by rubensworks** [comment]
I'm actually surprised this works.
This must mean that `npx` will make sure that the current package and `community-solid-server` are both available in the same Node scope.
We may want to document this.

(might also make Comunica and LDF server executions a lot easier)

**Comment by RubenVerborgh** [comment]
> I'm actually surprised this works.

With both installed in the local `node_modules` folder, that is.

**Comment by RubenVerborgh** [comment]
Actually, not fully true.

`npx community-solid-server -c settings.json -m .` works with
```shell
git clone git@github.com:RubenVerborgh/solid-hue.git
cd solid-hue
npm ci
```

but not with

```shell
mkdir my-server
cd my-server
npm install @solid/community-server@v0.4.0 solid-hue
```

In the latter case, it fails with

```
    details: {
      code: 'loading remote context failed',
      url: 'https://linkedsoftwaredependencies.org/bundles/npm/solid-hue/^1.0.0/components/context.jsonld',
      cause: [JsonLdError]
    }
```

whereas it shouldn't be loading remotely.
