### ISSUE TITLE
require is called several times for the same module

### ISSUE THREAD

**Issue by RubenVerborgh** [LinkedSoftwareDependencies/Components.js#31]
i noticed that the resolution code at https://github.com/LinkedSoftwareDependencies/Components.js/blob/71be00e742447ae702fd85ece1eeb461b344cf5d/lib/factory/UnnamedComponentFactory.ts#L181-L206 is executed multiple times for the same `requireName`, which can be costly.

Perhaps this should be a separate function with a cache?

**Comment by rubensworks** [comment]
There should actually already be a cache. But it's possible that it's not 100% effective during race conditions.
I'll look into it in the refactored version, it may already be fixed there.

In any case, `require` already [does some caching](https://nodejs.org/api/modules.html#modules_caching), so the problem should be limited.

**Comment by RubenVerborgh** [comment]
> There should actually already be a cache.

During debugging, I found it to be executing several times (dozens).

> In any case, `require` already [does some caching](https://nodejs.org/api/modules.html#modules_caching), so the problem should be limited.

True, but our own resolution mechanism is not cached.
