### ISSUE TITLE
Injecting functions

### ISSUE THREAD

**Issue by woutermont** [LinkedSoftwareDependencies/Components.js#45]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

Is it currently possible to somehow inject functions into components? If not, how hard would it be to implement?

**Comment by rubensworks** [comment]
Haven't used this feature myself yet, but this should be possible using `requireNoConstructor` as explained here: https://componentsjs.readthedocs.io/en/latest/configuration/configurations/nonsemantic/#example-single-argument-without-calling-the-constructor

**Comment by woutermont** [comment]
I'l definitely look into that! 

Do these non-semantic configurations always load the module from NPM, or can it take local packages as well?

What this feature seems to lack, is the ability to pass partial argument lists to a function (e.g. by currying them). I realize, however, that this could require too much of an abstraction from class constructors.

**Comment by rubensworks** [comment]
> Do these non-semantic configurations always load the module from NPM, or can it take local packages as well?

Components.js never fetched modules from NPM. It always loads them from the local `node_modules`.

> What this feature seems to lack, is the ability to pass partial argument lists to a function (e.g. by currying them). I realize, however, that this could require too much of an abstraction from class constructors.

Yeah, there's no functional programming support at all, one could go very far with this.
