### ISSUE TITLE
`null` parameters are converted to `undefined`

### ISSUE THREAD

**Issue by lem-onade** [LinkedSoftwareDependencies/Components.js#46]
#### Issue type:

- :bug: Bug 

____
#### Description:

`null` parameters are converted to `undefined`

Example:

```
{
  "@id": "http://example.org/myInstance",
  "@type": "ex:MyModule/MyComponent",
  "ex:MyModule/MyComponent#name": null
}
```
would create object

```
{ name: undefined }
```

Is this intentional?

____
#### Environment:
UNIX
Components.js v4.0.5
Components.js generator v2.1.0
Node.js v14

#### Crash log:
/

**Comment by rubensworks** [comment]
This is a consequence of the JSON-LD parsing algorithm.
JSON-LD will emit to RDF triple for a predicate with object set to `null`, which is the same as leaving it `undefined`.
This means that Components.js will either produce an error if it's a required paremeter, or `undefined` if it's optional.

In any case, I would recommend not attaching special meaning to `null` vs `undefined`.

**Comment by lem-onade** [comment]
Alright, thanks for the explanation!
