### ISSUE TITLE
Incorrect path generated when using compile-config.js in Windows

### ISSUE THREAD

**Issue by joachimvh** [LinkedSoftwareDependencies/Components.js#6]
When using compile-config.js to generate a compile file I got the following output

```typescript
const urn_comunica_sparqlinit = new (require('C:\projects\comunica\comunica\packages\actor-init-sparql\index.js').ActorInitSparql)({
  'mediatorQueryOperation': ex_mediatorQueryOperation,
  'mediatorSparqlParse': ex_mediatorSparlParse,
  'name': 'urn:comunica:sparqlinit',
  'bus': https___linkedsoftwaredependencies_org_bundles_npm__comunica_bus_init_Bus_Init
});
```

The problem is that the backslashes make the string interpretation incorrect. This is due to the fact that this is dynamically generated code. The backslashes should be escaped before being written to the file (or changed to forward slashes).

**Comment by RubenVerborgh** [comment]
Yeah, we need escaping in general, to avoid that malicious code can be injected.

Side-question: do we always bind to such very specific paths, or is there an option that only binds to an assumed npm path (and this results in a more portable config)?

**Comment by rubensworks** [comment]
At the moment, it's always an absolute path because that's easier in our monorepo setup.

But it's definitely possible to relative-ize these paths, I can look into that.

**Comment by RubenVerborgh** [comment]
Great, let's track that in a separate issue.

**Comment by rubensworks** [comment]
Created #7 for that.
