### ISSUE TITLE
Ontology: Support for Algebraic Data Types

### ISSUE THREAD

**Issue by damooo** [LinkedSoftwareDependencies/Components.js#69]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:
Feel free to close the issue, if it doesn't fit here in this repository. I cannot found any other place.
It seems lsd project and ontology is language agnostic. It will be great, if ontology supports expressing Algebraic data types, so that we can model rust's enums , or haskell's enums etc. with this ontology.

Thanks for your work.

**Comment by rubensworks** [comment]
You're in luck, support for this will be added in the 5.x release :-)
It will support all algebraic data types that are supported by TypeScript.

You can play around with it with the latest beta releases of this package and the Components.js-generator.

(Closing this issue in the meantime)
