### ISSUE TITLE
Incorrect character escaping when for input parameters when using compile-config

### ISSUE THREAD

**Issue by joachimvh** [LinkedSoftwareDependencies/Components.js#8]
ActorHttpNative has the following in its components jsonld file:
```json
      "parameters": [
        {
          "@id": "cbh:Actor/Http/Native/agentOptions",
          "comment": "The AgentOptions for the HTTP agent as a JSON string",
          "required": false,
          "unique": true,
          "default": "{ \"keepAlive\": true, \"maxSockets\": 5 }",
          "range": "xsd:string"
        }
      ],
```

The problem is the default value for agentOptions, which gets translated to the following:

```typescript
const ex_myHttpFetcher = new (require('@comunica/actor-http-native').ActorHttpNative)({
  'agentOptions': '{ \keepAlive\: true, \maxSockets\: 5 }',
  'name': 'ex:myHttpFetcher',
  'bus': https___linkedsoftwaredependencies_org_bundles_npm__comunica_bus_http_Bus_Http
});
```

The escaped `"` are missing, causing the string to be invalid JSON (which causes the JSON parser to fail a bit later in the code)

**Comment by rubensworks** [comment]
Released as version 2.1.3.

**Comment by joachimvh** [comment]
So I'm going to be the annoying person here that says this doesn't work for `"\"\\"` as far as I can see. Might be easier to just iterate over the fields to remove the outer `"` for each?

**Comment by rubensworks** [comment]
Just tested it, and `"\"\\"` still works actually.

> Might be easier to just iterate over the fields to remove the outer `"` for each?

Not really actually, as we have a JSON object to begin with. But this regex is temporary anyways, when we port to RDFJS (#1), literals won't be encoded in `"`'s anymore, so then we don't have to replace them anymore.

**Comment by joachimvh** [comment]
Ah yea, I had it wrong in my head, my mistake.
