### ISSUE TITLE
oo:componentPath should be made optional

### ISSUE THREAD

**Issue by LanderN** [LinkedSoftwareDependencies/Components.js#9]
Hello!
Like the title says, is it possible to invoke npm modules that directly export a function?
An example of such a module would be [this euclidean-distance package](https://www.npmjs.com/package/euclidean-distance).

Its `index.js` looks like this:
```javascript

var distanceSquared = require('./squared')

module.exports = function (a, b) {
  return Math.sqrt(distanceSquared(a,b))
}
```

Is it possible to describe and invoke this with Components.js, even though there is not really any "Component" there?

Thanks!

**Comment by rubensworks** [comment]
Hi!

The primary goal of Components.js is to _construct_ objects, after which can call functions on it yourself.
So in this case, the exported function should be seen as something that has already been instantiated, as is described in the [manual here](http://componentsjs.readthedocs.io/en/latest/configuration/components/general/#example-component-instance).

However, it might be possible to _hack_ a bit, and make Components.js see this function as a _constructor_. I haven't tested this myself, so I don't know if this would work. So if this is something you want, feel free to try it, and be sure to let me know if it works :)

**Comment by LanderN** [comment]
Thank you for the quick response!
I can see how this is not the goal of the project, I was hoping this could be used to invoke *any* npm package.
Anyway, I'll try your suggestions and see if it works well enough, although I might end up with a different solution.
Thanks again for your help!

**Comment by RubenVerborgh** [comment]
> I was hoping this could be used to invoke any npm package.

That's still the case, right? As @rubensworks says:

>> So in this case, the exported function should be seen as something that has already been instantiated

So we just treat the function as an exported object, and you can use it as-is.

**Comment by LanderN** [comment]
Oh right, I was interpreting the word object as a real "Object", as in, an instance of a class, not realizing that a function technically fits that definition in JavaScript.
Thanks for the clarification!

**Comment by LanderN** [comment]
Sorry to bother you again, but I am still struggling with this.

Here are the relevant parts of code:

`indentStringModule.jsonld` (simplified):
```javascript
{
  "@context": [...],
  "@id": "ex:indentStringNPM",
  "@type": "oo:Module",
  "doap:name": "indent-string",
  "oo:component": {
    "@id": "ex:indentStringNPMComponent",
    "@type": "oo:ComponentInstance",
    "rdfs:comment": "This component is the function that indents the string.",
    "oo:componentPath": "" // What should this be?
  }
}
```

`indent-string`'s `index.js`:
```javascript
module.exports = (str, count, opts) => {
  ...
  return str.replace(regex, options.indent.repeat(count));
};
```
(Trying to) instantiate the component:
```javascript
const Loader = require('componentsjs').Loader;
const loader = new Loader();
await loader.registerModuleResourcesUrl('indentStringModule.jsonld');
const Component = await loader.instantiateManually('http://example.com/indentStringNPMComponent',{})
```

The resulting error:
`Error: Failed to get module element  from module indent-string`
(Trying to do `object[]` in [UnnamedComponentFactory.ts, line 196](https://github.com/LinkedSoftwareDependencies/Components.js/blob/master/lib/factory/UnnamedComponentFactory.ts#L196) if I understand correctly)

I suppose the problem is with `oo:componentPath`/`requireElement` not allowing an empty value, but I think it should be empty in this case?
Is there a way around this? I've also tried `"oo:componentPath": "."` without any luck.

**Comment by rubensworks** [comment]
@LanderN You're right, `oo:componentPath` is too strict at the moment to support this. While it is required at the moment, it should indeed be made optional. I don't see a way around this at the moment, except for changing the source code yourself in case you're feeling adventurous :-)

(FYI, I won't be able to fix this until ~April 9)

Note to self: the problem lies here: https://github.com/LinkedSoftwareDependencies/Components.js/blob/master/lib/factory/UnnamedComponentFactory.ts#L193

**Comment by LanderN** [comment]
It does not seem too hard to remove that restriction, I'll try to do it and submit a pull request. 🙂 
What would the proper convention be to indicate an "empty" `oo:componentPath`? An empty string, a dot, some new `oo:emptyPath`, not specifying the property, or something else?

**Comment by rubensworks** [comment]
Sure, a PR on this would be great :-)

I would simply not specify the property if it's not needed, that feels like the most logical way to go.
(I might have to change some things in the ontology and documentation for this as well then)
